  branch-a[m
* [32mmaster[m
  medlog-crud[m
  my-medications-page[m
  third-party-api[m
  third-party-api-2[m
  [31mremotes/origin/HEAD[m -> origin/master
  [31mremotes/origin/a[m
  [31mremotes/origin/addbtn[m
  [31mremotes/origin/addmedformtextstyle[m
  [31mremotes/origin/addmedicationform[m
  [31mremotes/origin/addmeds[m
  [31mremotes/origin/adduser2nd[m
  [31mremotes/origin/api-routes[m
  [31mremotes/origin/appupates[m
  [31mremotes/origin/back-end-folders[m
  [31mremotes/origin/back-end-folders2[m
  [31mremotes/origin/branch-a[m
  [31mremotes/origin/btnmargin[m
  [31mremotes/origin/calendarbarimport[m
  [31mremotes/origin/card[m
  [31mremotes/origin/cardcenter[m
  [31mremotes/origin/class-name[m
  [31mremotes/origin/clientfolder[m
  [31mremotes/origin/clientroutes[m
  [31mremotes/origin/comment[m
  [31mremotes/origin/container[m
  [31mremotes/origin/dashboardcomponents[m
  [31mremotes/origin/dashboardlayout[m
  [31mremotes/origin/fix-models[m
  [31mremotes/origin/globalstate[m
  [31mremotes/origin/healthnav[m
  [31mremotes/origin/healthtab[m
  [31mremotes/origin/hello[m
  [31mremotes/origin/hi[m
  [31mremotes/origin/homepagecomponents[m
  [31mremotes/origin/homepagestyled[m
  [31mremotes/origin/infocardchange[m
  [31mremotes/origin/infocardsmobile[m
  [31mremotes/origin/initialcodeforpages[m
  [31mremotes/origin/jsonfile[m
  [31mremotes/origin/jumbotron[m
  [31mremotes/origin/login[m
  [31mremotes/origin/master[m
  [31mremotes/origin/med-form[m
  [31mremotes/origin/med-form2[m
  [31mremotes/origin/medLog-api[m
  [31mremotes/origin/medLog-model-1[m
  [31mremotes/origin/medformtext[m
  [31mremotes/origin/medicationform[m
  [31mremotes/origin/medicineapi[m
  [31mremotes/origin/medlog-crud[m
  [31mremotes/origin/medroutineapi[m
  [31mremotes/origin/medroutinemodel[m
  [31mremotes/origin/meds-branch[m
  [31mremotes/origin/meds-card[m
  [31mremotes/origin/minor-branch[m
  [31mremotes/origin/mobileaddmedications[m
  [31mremotes/origin/modal[m
  [31mremotes/origin/models[m
  [31mremotes/origin/mymeds[m
  [31mremotes/origin/nav-after-login[m
  [31mremotes/origin/navbarpublic[m
  [31mremotes/origin/navdashboardlink[m
  [31mremotes/origin/navpublicreact[m
  [31mremotes/origin/navroutes[m
  [31mremotes/origin/navstyle[m
  [31mremotes/origin/newfront[m
  [31mremotes/origin/reactnav[m
  [31mremotes/origin/server-js[m
  [31mremotes/origin/setstateafterlogin[m
  [31mremotes/origin/setstateafterlogin2[m
  [31mremotes/origin/signup[m
  [31mremotes/origin/signup-page[m
  [31mremotes/origin/signupcenter[m
  [31mremotes/origin/startingcodeforpages[m
  [31mremotes/origin/storeprovider[m
  [31mremotes/origin/third-party-api[m
  [31mremotes/origin/third-party-api-2[m
  [31mremotes/origin/tryingfronend[m
  [31mremotes/origin/user-api[m
  [31mremotes/origin/user-crud[m
  [31mremotes/origin/usermodel[m
  [31mremotes/origin/validateMedandMedroutine[m
