export const FETCHING_ARTICLES = "FETCHING_ARTICLES";
export const FETCHED_ARTICLES = "FETCHED_ARTICLES";
export const ADD_ARTICLES = "ADD_ARTICLES";

export const USER_SIGN_UP = "USER_SIGN_UP";
export const USER_LOG_IN = "USER_LOG_IN"
;

